import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.className} bg-zinc-200 dark:bg-zinc-800 text-zinc-800 dark:text-zinc-200`}>{children}</body>
    </html>
  )
}
